name: Example
description: An example adapter that does something.
node_identifier: bwexample
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Example
    url: https://example.com
parameters:
  - base
  - quote
